"""Generate deterministic manifests, docs, and boilerplate READMEs from code registries."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.registry.commands import command_manifest_payload, command_registry
from src.registry.dashboard_routes import dashboard_route_manifest_payload, dashboard_routes, staging_dashboard_routes
from src.registry.leagues import league_manifest_payload, ordered_league_entries
from src.registry.models import model_manifest_payload, ordered_model_entries
from src.registry.subsystems import subsystem_docs


ROOT_DIR = Path(__file__).resolve().parents[2]
MARKDOWN_HEADER = "<!-- Generated by src.registry.generate. Do not edit by hand. -->"
CODEGEN_HEADER = "/* Generated by src.registry.generate. Do not edit by hand. */"


def _json_text(payload: dict[str, object]) -> str:
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def _ts_value(value: object, *, indent: int = 0) -> str:
    spacer = " " * indent
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        inner = ",\n".join(f"{' ' * (indent + 2)}{_ts_value(item, indent=indent + 2)}" for item in value)
        return "[\n" + inner + f"\n{spacer}]"
    if isinstance(value, tuple):
        return _ts_value(list(value), indent=indent)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for key, item in value.items():
            lines.append(f"{' ' * (indent + 2)}{key}: {_ts_value(item, indent=indent + 2)}")
        return "{\n" + ",\n".join(lines) + f"\n{spacer}}}"
    raise TypeError(f"Unsupported TS literal value: {type(value)!r}")


def _ts_string_map(values: dict[str, str]) -> str:
    items = ",\n".join(f'  {json.dumps(key)}: {json.dumps(value)}' for key, value in values.items())
    return "{\n" + items + "\n}"


def _generated_league_ts() -> str:
    entries = ordered_league_entries()
    all_leagues = [entry.code for entry in entries]
    alias_map: dict[str, str] = {}
    runtime: dict[str, object] = {}
    for entry in entries:
        alias_map[entry.code] = entry.code
        alias_map[entry.slug.upper()] = entry.code
        for alias in entry.aliases:
            alias_map[alias.upper()] = entry.code
        runtime[entry.code] = {
            "code": entry.code,
            "slug": entry.slug,
            "displayLabel": entry.display_label,
            "defaultConfigPath": entry.default_config_path,
            "configEnvVar": entry.config_env_var,
            "projectName": entry.project_name,
            "dbPath": entry.db_path,
            "dbEnvVar": entry.db_env_var,
            "championshipName": entry.championship_name,
            "championshipProbabilityKey": entry.championship_probability_key,
            "uncertaintyPolicyName": entry.uncertainty_policy_name,
            "aliases": list(entry.aliases),
        }
    return "\n".join(
        [
            f"{CODEGEN_HEADER}",
            "",
            "export const ALL_LEAGUES = " + _ts_value(all_leagues) + " as const;",
            "export type LeagueCode = typeof ALL_LEAGUES[number];",
            "",
            "export type LeagueRuntimeEntry = {",
            "  code: LeagueCode;",
            "  slug: string;",
            "  displayLabel: string;",
            "  defaultConfigPath: string;",
            "  configEnvVar: string;",
            "  projectName: string;",
            "  dbPath: string;",
            "  dbEnvVar: string;",
            "  championshipName: string;",
            "  championshipProbabilityKey: string;",
            "  uncertaintyPolicyName: string;",
            "  aliases: readonly string[];",
            "};",
            "",
            "export const LEAGUE_ALIASES: Record<string, LeagueCode> = " + _ts_string_map(alias_map) + ";",
            "export const LEAGUE_RUNTIME: Record<LeagueCode, LeagueRuntimeEntry> = "
            + _ts_value(runtime)
            + ";",
            "",
        ]
    ) + "\n"


def _generated_model_ts() -> str:
    payload = model_manifest_payload()
    model_registry = payload["models"]
    return "\n".join(
        [
            f"{CODEGEN_HEADER}",
            "",
            "export const TRAINABLE_MODELS = " + _ts_value(payload["trainable_models"]) + " as const;",
            "export type TrainableModel = typeof TRAINABLE_MODELS[number];",
            "",
            "export const MODEL_ALIASES: Record<string, string> = " + _ts_value(payload["aliases"]) + ";",
            "export const LEGACY_MODEL_KEYS: Record<string, readonly string[]> = "
            + _ts_value(payload["legacy_model_keys"])
            + ";",
            "export const MODEL_REPORT_ORDER = " + _ts_value(payload["prediction_report_order"]) + " as const;",
            "export const MODEL_DISPLAY_LABELS: Record<string, string> = " + _ts_value(payload["display_labels"]) + ";",
            "export const MODEL_REGISTRY = " + _ts_value(model_registry) + ";",
            "",
        ]
    ) + "\n"


def _generated_dashboard_routes_ts() -> str:
    routes = []
    for route in dashboard_routes():
        routes.append(
            {
                "key": route.key,
                "summary": route.summary,
                "modulePath": route.module_path,
                "apiPath": route.api_path,
                "pagePath": route.page_path,
                "stagingFileName": route.staging_file_name,
                "payloadContract": route.payload_contract,
                "includeInStaging": route.include_in_staging,
                "public": route.public,
                "supportsExperiments": route.supports_experiments,
            }
        )
    staging_keys = [route.key for route in staging_dashboard_routes()]
    return "\n".join(
        [
            f"{CODEGEN_HEADER}",
            "",
            "export const DASHBOARD_ROUTE_KEYS = " + _ts_value([route["key"] for route in routes]) + " as const;",
            "export type DashboardRouteKey = typeof DASHBOARD_ROUTE_KEYS[number];",
            "",
            "export type DashboardRouteEntry = {",
            "  key: DashboardRouteKey;",
            "  summary: string;",
            "  modulePath: string;",
            "  apiPath: string;",
            "  pagePath: string | null;",
            "  stagingFileName: string;",
            "  payloadContract: DashboardRouteKey;",
            "  includeInStaging: boolean;",
            "  public: boolean;",
            "  supportsExperiments: boolean;",
            "};",
            "",
            "export const DASHBOARD_ROUTES: readonly DashboardRouteEntry[] = " + _ts_value(routes) + ";",
            "export const DASHBOARD_STAGING_ROUTE_KEYS = " + _ts_value(staging_keys) + " as const;",
            "export const DASHBOARD_STAGING_ROUTES = DASHBOARD_ROUTES.filter((route) => route.includeInStaging);",
            "",
        ]
    ) + "\n"


def _architecture_doc() -> str:
    rows = [
        "| Path | Role | Public Entrypoints |",
        "| --- | --- | --- |",
    ]
    for entry in subsystem_docs():
        rows.append(
            f"| `{entry.path}` | {entry.summary} | {', '.join(f'`{item}`' for item in entry.public_entrypoints)} |"
        )
    return "\n".join(
        [
            MARKDOWN_HEADER,
            "",
            "# Generated Architecture Map",
            "",
            "This reference is generated from the code registries. Update the registry modules, then regenerate docs.",
            "",
            *rows,
            "",
        ]
    )


def _command_doc() -> str:
    sections = [MARKDOWN_HEADER, "", "# Generated Command Reference", ""]
    for entry in command_registry():
        sections.extend([f"## `{entry.name}`", "", entry.summary, ""])
        sections.append(f"- Default config: `{command_manifest_payload()['default_config_path']}`")
        if entry.arguments:
            sections.append("- Options:")
            for argument in entry.arguments:
                label = ", ".join(f"`{flag}`" for flag in argument.flags)
                hint = f" `{argument.doc_metavar}`" if argument.doc_metavar else ""
                sections.append(f"  - {label}{hint}: {argument.argparse_kwargs.get('help', '')}")
        if entry.examples:
            sections.append("- Examples:")
            for example in entry.examples:
                sections.append(f"  - `{example}`")
        sections.append("")
    return "\n".join(sections).rstrip() + "\n"


def _dashboard_route_doc() -> str:
    rows = [
        "| Key | API Path | Staging File | Page | Experiments |",
        "| --- | --- | --- | --- | --- |",
    ]
    for route in dashboard_routes():
        rows.append(
            f"| `{route.key}` | `{route.api_path}` | `{route.staging_file_name}` | "
            f"{'`' + route.page_path + '`' if route.page_path else 'n/a'} | "
            f"{'yes' if route.supports_experiments else 'no'} |"
        )
    return "\n".join(
        [
            MARKDOWN_HEADER,
            "",
            "# Generated Dashboard Route Reference",
            "",
            "All dashboard API and staging routes are derived from the code-first dashboard route registry.",
            "",
            *rows,
            "",
        ]
    )


def _extensions_doc() -> str:
    league_codes = ", ".join(f"`{entry.code}`" for entry in ordered_league_entries())
    model_keys = ", ".join(f"`{entry.key}`" for entry in ordered_model_entries())
    route_keys = ", ".join(f"`{route.key}`" for route in dashboard_routes())
    return "\n".join(
        [
            MARKDOWN_HEADER,
            "",
            "# Generated Extension Guide",
            "",
            "## Add A League",
            "",
            "1. Register the new league in `src/registry/leagues.py`.",
            "2. Add league-specific adapters and feature/query support behind existing public entrypoints.",
            "3. Regenerate manifests and docs with `make docs-generate`.",
            "4. Extend cross-league tests and dashboard/staging coverage until verification passes.",
            "",
            f"Current leagues: {league_codes}.",
            "",
            "## Add A Model",
            "",
            "1. Register the model in `src/registry/models.py` with aliases, labels, and report order.",
            "2. Implement training/report behavior behind existing model contracts.",
            "3. Regenerate manifests and docs, then extend model contract tests.",
            "",
            f"Current registered models: {model_keys}.",
            "",
            "## Add A Dashboard Payload",
            "",
            "1. Register the API/staging route in `src/registry/dashboard_routes.py`.",
            "2. Implement the route module and payload contract in the web app.",
            "3. Regenerate manifests/docs, then update route and staging contract tests.",
            "",
            f"Current registered dashboard routes: {route_keys}.",
            "",
        ]
    )


def _manifest_doc() -> str:
    return "\n".join(
        [
            MARKDOWN_HEADER,
            "",
            "# Generated Manifest Inventory",
            "",
            "- `configs/generated/league_manifest.json`: canonical league metadata for Python, web, and docs consumers.",
            "- `configs/generated/model_manifest.json`: canonical model labels, aliases, ordering, and trainable-model set.",
            "- `configs/generated/command_manifest.json`: canonical CLI command metadata and examples.",
            "- `configs/generated/dashboard_route_manifest.json`: canonical dashboard API/staging route inventory.",
            "- `web/lib/generated/*.ts`: generated TypeScript registry surfaces derived from the same Python source registries.",
            "",
        ]
    )


def _generated_readme(entry_path: str, title: str, summary: str, public_entrypoints: tuple[str, ...], notes: tuple[str, ...]) -> str:
    lines = [
        MARKDOWN_HEADER,
        "",
        f"# {title}",
        "",
        summary,
        "",
        "Public entrypoints:",
    ]
    for item in public_entrypoints:
        lines.append(f"- `{item}`")
    if notes:
        lines.extend(["", "Notes:"])
        for note in notes:
            lines.append(f"- {note}")
    lines.extend(
        [
            "",
            f"This README is generated from the subsystem registry entry for `{entry_path}`.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, *, check: bool, changed_paths: list[Path]) -> None:
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return
    changed_paths.append(path)
    if check:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate_all(*, root_dir: Path = ROOT_DIR, check: bool = False) -> list[Path]:
    """Generate or validate all registry-backed artifacts."""

    changed_paths: list[Path] = []
    manifest_dir = root_dir / "configs" / "generated"
    docs_dir = root_dir / "docs" / "generated"
    web_generated_dir = root_dir / "web" / "lib" / "generated"

    outputs: dict[Path, str] = {
        manifest_dir / "league_manifest.json": _json_text(league_manifest_payload()),
        manifest_dir / "model_manifest.json": _json_text(model_manifest_payload()),
        manifest_dir / "command_manifest.json": _json_text(command_manifest_payload()),
        manifest_dir / "dashboard_route_manifest.json": _json_text(dashboard_route_manifest_payload()),
        docs_dir / "architecture.md": _architecture_doc(),
        docs_dir / "commands.md": _command_doc(),
        docs_dir / "dashboard-routes.md": _dashboard_route_doc(),
        docs_dir / "extensions.md": _extensions_doc(),
        docs_dir / "manifests.md": _manifest_doc(),
        web_generated_dir / "league-registry.ts": _generated_league_ts(),
        web_generated_dir / "model-manifest.ts": _generated_model_ts(),
        web_generated_dir / "dashboard-routes.ts": _generated_dashboard_routes_ts(),
    }

    for entry in subsystem_docs():
        if entry.generate_readme and entry.readme_path:
            outputs[root_dir / entry.readme_path] = _generated_readme(
                entry.path,
                entry.title,
                entry.summary,
                entry.public_entrypoints,
                entry.notes,
            )

    for path, content in outputs.items():
        _write_or_check(path, content, check=check, changed_paths=changed_paths)

    return changed_paths


def main() -> None:
    """Generate or check deterministic registry-backed artifacts."""

    parser = argparse.ArgumentParser(description="Generate registry-backed manifests, docs, and boilerplate READMEs.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated artifacts are stale instead of rewriting them.",
    )
    args = parser.parse_args()

    changed_paths = generate_all(check=bool(args.check))
    if args.check and changed_paths:
        for path in changed_paths:
            print(path.relative_to(ROOT_DIR))
        raise SystemExit(1)


if __name__ == "__main__":
    main()
