#!/usr/bin/env python3
"""Generate a bounded MLB fixture slice through the real artifact paths.

This script is intentionally narrow: it creates a deterministic, pregame-legal
MLB feature slice only when local production features are absent or `--force`
is provided, then calls the real candidate-comparison and validation services.
The resulting outputs are labeled as fixture/slice evidence, not production
model evidence.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from src.common.config import load_config
from src.common.time import utc_now_iso
from src.common.utils import ensure_dir, to_json
from src.evaluation.validation_pipeline import run_validation_pipeline
from src.services.model_compare import compare_candidate_models
from src.storage.db import Database
from src.training.feature_selection import select_feature_columns


COMPARISON_ARTIFACT_PATH_KEYS = (
    "report_path",
    "summary_path",
    "validation_metrics_path",
    "test_metrics_path",
    "bootstrap_path",
    "fit_stats_path",
    "cv_path",
    "screening_path",
    "nonlinearity_path",
    "validation_predictions_path",
    "test_predictions_path",
    "candidate_scorecards_path",
    "candidate_scorecards_contract_path",
    "leaderboard_path",
    "leaderboard_json_path",
    "recommendation_path",
    "recommendation_surface_path",
    "artifact_manifest_path",
    "mlb_service_output_path",
    "mlb_service_manifest_path",
)

TEAMS = (
    "ARI",
    "ATL",
    "BAL",
    "BOS",
    "CHC",
    "CIN",
    "CLE",
    "COL",
    "DET",
    "HOU",
    "LAD",
    "MIL",
    "MIN",
    "NYM",
    "NYY",
    "PHI",
)


def _logit(probability: np.ndarray) -> np.ndarray:
    clipped = np.clip(probability, 1e-6, 1.0 - 1e-6)
    return np.log(clipped / (1.0 - clipped))


def _reports_dir(cfg) -> Path:
    return Path(cfg.paths.artifacts_dir) / "reports" / "mlb"


def _reports_history_dir(cfg) -> Path:
    return Path(cfg.paths.artifacts_dir) / "reports" / "history"


def _validation_dir(cfg) -> Path:
    return Path(cfg.paths.artifacts_dir) / "validation" / "mlb"


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError:
        return False
    return True


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def _format_path_map(paths: dict[str, Path]) -> str:
    return ", ".join(f"{key}={path}" for key, path in sorted(paths.items()))


def _normalized_fixture_metadata(metadata: dict[str, Any]) -> dict[str, Any]:
    if "production_grade" in metadata:
        return metadata
    execution_metadata = metadata.get("execution_metadata", {})
    if not isinstance(execution_metadata, dict):
        return metadata
    normalized = dict(execution_metadata)
    for key in ("execution_data_scope", "execution_source_label", "source_label", "execution_label_class"):
        if key in metadata:
            normalized[key] = metadata[key]
    return normalized


def _fixture_execution_metadata(*, frame: pd.DataFrame, cfg) -> dict[str, Any]:
    return {
        "execution_data_scope": "mlb_fixture_slice",
        "execution_source_label": "deterministic MLB fixture slice generated by scripts/generate_mlb_artifact_slice.py",
        "source_label": "deterministic MLB fixture slice generated by scripts/generate_mlb_artifact_slice.py",
        "execution_label_class": "fixture_or_demo",
        "data_origin": "synthetic_fixture",
        "production_grade": False,
        "fixture_rows": int(len(frame)),
        "feature_count": int(len(select_feature_columns(frame))),
        "artifact_purpose": "prove real MLB report and validation artifact paths through real services",
        "required_comparison_output_dir": str(_reports_dir(cfg)),
        "required_validation_output_dir": str(_validation_dir(cfg)),
        "full_mlb_blocker": (
            "Local MLB processed features and historical manifest were absent in this worktree; "
            "this run uses a bounded fixture slice instead of claiming production data coverage."
        ),
    }


def _assert_fixture_metadata(metadata: dict[str, Any]) -> None:
    normalized = _normalized_fixture_metadata(metadata)
    scope = str(normalized.get("execution_data_scope") or "")
    source = str(normalized.get("execution_source_label") or normalized.get("source_label") or "")
    label_class = str(normalized.get("execution_label_class") or "")
    if normalized.get("production_grade") is not False:
        raise RuntimeError("Fixture slice metadata must set production_grade=false.")
    if label_class != "fixture_or_demo":
        raise RuntimeError("Fixture slice metadata must set execution_label_class='fixture_or_demo'.")
    if "fixture" not in f"{scope} {source}".lower():
        raise RuntimeError("Fixture slice metadata must clearly label the execution as fixture data.")


def _comparison_artifact_paths(comparison, summary_payload: dict[str, Any]) -> dict[str, Path]:
    paths: dict[str, Path] = {}
    direct_attrs = {
        "report_path": getattr(comparison, "report_path", None),
        "summary_path": getattr(comparison, "summary_path", None),
        "candidate_scorecards_path": getattr(comparison, "candidate_scorecards_path", None),
        "candidate_scorecards_contract_path": getattr(comparison, "candidate_scorecards_contract_path", None),
        "recommendation_path": getattr(comparison, "recommendation_path", None),
        "validation_metrics_path": getattr(comparison, "validation_metrics_path", None),
        "test_metrics_path": getattr(comparison, "test_metrics_path", None),
        "bootstrap_path": getattr(comparison, "bootstrap_path", None),
        "fit_stats_path": getattr(comparison, "fit_stats_path", None),
        "cv_path": getattr(comparison, "cv_path", None),
        "leaderboard_path": getattr(comparison, "leaderboard_path", None),
        "leaderboard_json_path": getattr(comparison, "leaderboard_json_path", None),
        "recommendation_surface_path": getattr(comparison, "recommendation_surface_path", None),
        "artifact_manifest_path": getattr(comparison, "artifact_manifest_path", None),
    }
    for key, value in direct_attrs.items():
        if value:
            paths[key] = Path(value)

    artifacts = summary_payload.get("artifacts", {})
    if isinstance(artifacts, dict):
        for key in COMPARISON_ARTIFACT_PATH_KEYS:
            value = artifacts.get(key)
            if value:
                paths[key] = Path(str(value))
    return paths


def _validate_comparison_outputs(cfg, comparison, *, metadata: dict[str, Any]) -> dict[str, str]:
    _assert_fixture_metadata(metadata)
    summary_payload = _load_json(Path(comparison.summary_path))
    execution_metadata = summary_payload.get("metadata", {}).get("execution_metadata", {})
    if not isinstance(execution_metadata, dict):
        raise RuntimeError("Comparison summary did not preserve fixture execution metadata.")
    _assert_fixture_metadata(execution_metadata)

    reports_dir = _reports_dir(cfg)
    history_dir = _reports_history_dir(cfg)
    material_paths = _comparison_artifact_paths(comparison, summary_payload)
    history_paths = {key: path for key, path in material_paths.items() if _is_relative_to(path, history_dir)}
    if history_paths:
        raise RuntimeError(
            "MLB fixture slice comparison outputs must not point at artifacts/reports/history: "
            f"{_format_path_map(history_paths)}"
        )
    outside_reports = {key: path for key, path in material_paths.items() if not _is_relative_to(path, reports_dir)}
    if outside_reports:
        raise RuntimeError(
            "MLB fixture slice comparison outputs must resolve under artifacts/reports/mlb: "
            f"{_format_path_map(outside_reports)}"
        )
    missing = {key: path for key, path in material_paths.items() if not path.exists()}
    if missing:
        raise RuntimeError(f"MLB fixture slice comparison outputs are missing: {_format_path_map(missing)}")
    return {key: str(path) for key, path in sorted(material_paths.items())}


def _validate_validation_outputs(cfg, *, metadata: dict[str, Any]) -> dict[str, Any]:
    _assert_fixture_metadata(metadata)
    validation_dir = _validation_dir(cfg)
    required = {
        "validation_manifest": validation_dir / "validation_manifest.json",
        "validation_outputs_contract": validation_dir / "validation_outputs_contract.json",
        "validation_run_metadata": validation_dir / "validation_run_metadata.json",
    }
    missing = {key: path for key, path in required.items() if not path.exists()}
    if missing:
        raise RuntimeError(f"MLB fixture slice validation outputs are missing: {_format_path_map(missing)}")

    run_metadata = _load_json(required["validation_run_metadata"])
    _assert_fixture_metadata(run_metadata)
    latest_validation_dir = Path(cfg.paths.artifacts_dir) / str(run_metadata.get("latest_validation_dir", ""))
    if not _is_relative_to(latest_validation_dir, validation_dir):
        raise RuntimeError(
            "MLB fixture slice validation metadata must point latest_validation_dir at artifacts/validation/mlb: "
            f"{latest_validation_dir}"
        )
    return run_metadata


def build_fixture_frame(*, n_games: int, seed: int) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    start = pd.Timestamp("2025-03-27T18:05:00Z")
    rows: list[dict[str, Any]] = []

    for idx in range(n_games):
        game_start = start + pd.Timedelta(days=idx // 8, hours=idx % 8)
        home_idx = idx % len(TEAMS)
        away_idx = (idx * 5 + 3) % len(TEAMS)
        if away_idx == home_idx:
            away_idx = (away_idx + 1) % len(TEAMS)

        team_strength_edge = rng.normal(0.0, 0.55)
        starter_quality_edge = rng.normal(0.0, 0.45)
        bullpen_quality_edge = rng.normal(0.0, 0.35)
        bullpen_fatigue_edge = rng.normal(0.0, 0.30)
        lineup_quality_edge = rng.normal(0.0, 0.40)
        recent_offense_edge = rng.normal(0.0, 0.45)
        recent_defense_edge = rng.normal(0.0, 0.35)
        park_run_factor = float(np.clip(rng.normal(1.0, 0.07), 0.82, 1.22))
        rest_edge = rng.integers(-2, 3)
        travel_miles_edge = rng.normal(0.0, 750.0)
        timezone_edge = rng.integers(-3, 4)
        temperature_f = float(np.clip(rng.normal(72.0, 12.0), 38.0, 103.0))
        wind_out_mph = float(np.clip(rng.normal(4.0, 7.0), -14.0, 22.0))
        day_game = 1 if game_start.hour < 22 else 0
        division_game = 1 if home_idx // 4 == away_idx // 4 else 0
        market_noise = rng.normal(0.0, 0.28)

        linear_signal = (
            0.18
            + 0.42 * team_strength_edge
            + 0.34 * starter_quality_edge
            + 0.22 * bullpen_quality_edge
            - 0.28 * bullpen_fatigue_edge
            + 0.24 * lineup_quality_edge
            + 0.18 * recent_offense_edge
            + 0.14 * recent_defense_edge
            + 0.06 * rest_edge
            - 0.00020 * travel_miles_edge
            - 0.035 * timezone_edge
            + 0.12 * (park_run_factor - 1.0)
            + 0.006 * (temperature_f - 72.0)
            + 0.012 * wind_out_mph
            - 0.08 * day_game
            + 0.05 * division_game
        )
        model_probability = float(1.0 / (1.0 + np.exp(-linear_signal)))
        market_probability = float(1.0 / (1.0 + np.exp(-(linear_signal + market_noise) * 0.85)))
        home_win = int(rng.random() < model_probability)
        margin_base = 1.5 + 1.8 * abs(linear_signal) + rng.normal(0.0, 1.1)
        home_score = max(0, int(round(4.2 + margin_base * (1 if home_win else -0.35) + rng.normal(0.0, 1.0))))
        away_score = max(0, int(round(4.1 + margin_base * (0.35 if home_win else 1) + rng.normal(0.0, 1.0))))
        if home_win and home_score <= away_score:
            home_score = away_score + 1
        if not home_win and away_score <= home_score:
            away_score = home_score + 1

        rows.append(
            {
                "game_id": 910000 + idx,
                "season": 2025,
                "game_date_utc": game_start.date().isoformat(),
                "start_time_utc": game_start.isoformat().replace("+00:00", "Z"),
                "available_as_of_utc": (game_start - pd.Timedelta(hours=8)).isoformat().replace("+00:00", "Z"),
                "home_team": TEAMS[home_idx],
                "away_team": TEAMS[away_idx],
                "venue": f"Fixture Park {home_idx % 4 + 1}",
                "status_final": 1,
                "home_score": home_score,
                "away_score": away_score,
                "home_win": home_win,
                "team_strength_edge": team_strength_edge,
                "starter_quality_edge": starter_quality_edge,
                "starter_uncertainty_index": float(np.clip(rng.beta(2.0, 8.0), 0.0, 1.0)),
                "bullpen_quality_edge": bullpen_quality_edge,
                "bullpen_fatigue_edge": bullpen_fatigue_edge,
                "lineup_quality_edge": lineup_quality_edge,
                "lineup_uncertainty_index": float(np.clip(rng.beta(2.5, 7.5), 0.0, 1.0)),
                "recent_offense_edge": recent_offense_edge,
                "recent_defense_edge": recent_defense_edge,
                "park_run_factor": park_run_factor,
                "rest_edge": rest_edge,
                "travel_miles_edge": travel_miles_edge,
                "timezone_edge": timezone_edge,
                "temperature_f": temperature_f,
                "wind_out_mph": wind_out_mph,
                "day_game": day_game,
                "division_game": division_game,
                "market_vig_free_home_prob": market_probability,
                "market_logit_home_prob": float(_logit(np.asarray([market_probability]))[0]),
                "market_open_home_prob": float(np.clip(market_probability + rng.normal(0.0, 0.035), 0.05, 0.95)),
                "market_movement_home_prob": rng.normal(0.0, 0.035),
                "bookmaker_dispersion_home_prob": float(np.clip(abs(rng.normal(0.025, 0.015)), 0.0, 0.10)),
                "time_to_first_pitch_hours": 8.0,
            }
        )

    return pd.DataFrame(rows)


def _write_fixture_inputs(cfg, frame: pd.DataFrame, *, force: bool, metadata: dict[str, Any]) -> Path:
    processed_dir = ensure_dir(Path(cfg.paths.processed_dir))
    features_csv = processed_dir / "features.csv"
    features_parquet = processed_dir / "features.parquet"
    existing = [path for path in (features_csv, features_parquet) if path.exists()]
    if existing and not force:
        found = ", ".join(str(path) for path in existing)
        raise FileExistsError(f"Refusing to overwrite existing MLB processed features without --force: {found}")
    if features_parquet.exists() and force:
        features_parquet.unlink()
    frame.to_csv(features_csv, index=False)
    (processed_dir / "fixture_slice_metadata.json").write_text(to_json(metadata) + "\n")
    return features_csv


def _initialize_fixture_db(cfg, frame: pd.DataFrame, *, metadata: dict[str, Any]) -> None:
    db = Database(cfg.paths.db_path)
    db.init_schema()
    created_at = utc_now_iso()
    feature_cols = select_feature_columns(frame)
    db.execute(
        """
        INSERT OR REPLACE INTO feature_sets(
          feature_set_version, created_at_utc, snapshot_id, feature_columns_json, metadata_json
        ) VALUES (?, ?, ?, ?, ?)
        """,
        (
            "mlb_fixture_slice_v1",
            created_at,
            "mlb_fixture_slice_snapshot",
            json.dumps(feature_cols, sort_keys=True),
            to_json(metadata),
        ),
    )
    game_rows = []
    result_rows = []
    for row in frame.itertuples(index=False):
        game_rows.append(
            (
                int(row.game_id),
                int(row.season),
                str(row.game_date_utc),
                str(row.start_time_utc),
                "FINAL",
                str(row.home_team),
                str(row.away_team),
                None,
                None,
                str(row.venue),
                0,
                int(row.home_score),
                int(row.away_score),
                0,
                0,
                int(row.home_win),
                1,
                created_at,
            )
        )
        result_rows.append(
            (
                int(row.game_id),
                int(row.season),
                str(row.game_date_utc),
                str(row.start_time_utc),
                str(row.home_team),
                str(row.away_team),
                int(row.home_score),
                int(row.away_score),
                int(row.home_win),
                created_at,
            )
        )
    db.executemany(
        """
        INSERT OR REPLACE INTO games(
          game_id, season, game_date_utc, start_time_utc, game_state, home_team, away_team,
          home_team_id, away_team_id, venue, is_neutral_site, home_score, away_score,
          went_ot, went_so, home_win, status_final, as_of_utc
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        game_rows,
    )
    db.executemany(
        """
        INSERT OR REPLACE INTO results(
          game_id, season, game_date_utc, final_utc, home_team, away_team,
          home_score, away_score, home_win, ingested_at_utc
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        result_rows,
    )


def _run_validation_slice(cfg, frame: pd.DataFrame, *, report_slug: str, metadata: dict[str, Any]) -> None:
    feature_cols = select_feature_columns(frame)
    run_payload = {
        "model_run_id": f"{report_slug}_validation_fixture_run",
        "feature_set_version": "mlb_fixture_slice_v1",
        "selected_models": ["glm_ridge"],
        "glm_primary_model": "glm_ridge",
        "feature_columns": feature_cols,
        "model_feature_columns": {"glm_ridge": feature_cols},
        "glm_tuning_by_model": {"glm_ridge": {"best_c": 1.0, "best_l1_ratio": None}},
        "metadata": {"execution_metadata": metadata},
    }
    run_validation_pipeline(
        {
            "models": {},
            "train_df": frame,
            "feature_columns": feature_cols,
            "run_payload": run_payload,
        },
        cfg,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate real MLB fixture-slice artifacts through repo services.")
    parser.add_argument("--config", default="configs/mlb.yaml")
    parser.add_argument("--report-slug", default="mlb_fixture_slice_artifact_proof")
    parser.add_argument("--n-games", type=int, default=480)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    cfg = load_config(args.config)
    if str(cfg.data.league).upper() != "MLB":
        raise ValueError("This fixture artifact runner is intentionally MLB-only.")

    frame = build_fixture_frame(n_games=int(args.n_games), seed=int(args.seed))
    metadata = _fixture_execution_metadata(frame=frame, cfg=cfg)
    features_path = _write_fixture_inputs(cfg, frame, force=bool(args.force), metadata=metadata)
    _initialize_fixture_db(cfg, frame, metadata=metadata)

    comparison = compare_candidate_models(
        cfg,
        report_slug=str(args.report_slug),
        bootstrap_samples=100,
        candidate_models=["glm_ridge", "glm_lasso", "glm_elastic_net", "glm_vanilla"],
        feature_pool="full_screened",
        execution_metadata=metadata,
    )
    comparison_outputs = _validate_comparison_outputs(cfg, comparison, metadata=metadata)
    _run_validation_slice(cfg, frame, report_slug=str(args.report_slug), metadata=metadata)
    validation_metadata = _validate_validation_outputs(cfg, metadata=metadata)

    payload = {
        "status": "ok",
        "features_path": str(features_path),
        "comparison_report_path": str(comparison.report_path),
        "comparison_summary_path": str(comparison.summary_path),
        "comparison_outputs": comparison_outputs,
        "validation_dir": str(_validation_dir(cfg)),
        "validation_run_metadata_path": str(_validation_dir(cfg) / "validation_run_metadata.json"),
        "validation_archive_dir": str(validation_metadata.get("archive_dir") or ""),
        "reports_dir": str(_reports_dir(cfg)),
        "execution_metadata": metadata,
    }
    print("MLB_ARTIFACT_SLICE::" + json.dumps(payload, sort_keys=True))


if __name__ == "__main__":
    main()
